apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app:  webapp
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: faouzi0007/webapp:34
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: webapp-svc
spec:
  selector:
    app: webapp
  ports:
    - protocol: "TCP"
      port: 9001 # The port that the service is running on in the cluster
      targetPort: 9001 # The port exposed by the service
  type: NodePort # type of the service.
